import Head from "next/head";
import React, { useContext } from "react";
import { Context } from "../context/context";
import LoginSignUp from "../components/LoginSignUp";
import Chats from "../components/chats";
export default function Auth() {
  const {setUserName, setSecret } = useContext(Context);
  return (
    <div>
      <Head>
        <title>Chick chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginSignUp />
      {/* <Chats /> */}
    </div>
  );
}
